Annotation Processor: Sidecar Generator
fujaba/fulibFx pull request #76
Opened 2024-04-01 12:45 UTC by Clashsoft

## New Features

+ Added Sidecars, which are companion classes for controllers and components that implement the behavior of various annotations as regular but generated code.

Sidecars are a performance and understandability improvement over the reflection code that is currently used. Instead of several reflective calls to methods annotated with OnInit, OnRender, Param, etc., these methods are collected at compile time and their calls including proper parameter injection are generated into the Sidecar class. At runtime, the ControllerManager can check for existing Sidecar classes (for a component `FooComponent`, the sidecar class will always be called `FooComponent_Fx`), and statically invoke the predefined methods for init, render, destroy, resources, title, etc.. If no sidecar exists, the manager can fall back to reflection.

Benefits:
+ No runtime reflection necessary, apart from finding the Sidecar class once per component class.
+ Easily readable Stack Traces and debugging.
+ Better performance from static calls instead of reflection.

Drawbacks:
- Potential for differences in some implementation details (e.g. order of method calls, edge cases).
- Re-implementation effort (most of it is already done).
- All annotated methods and fields must be at least package-private.

If we want to enforce the use of the annotation processor, we can even remove all reflective implementations entirely.

2024-04-06 18:13 UTC, LeStegii requested changes

2024-04-06 18:13 UTC, LeStegii commented on framework/src/test/java/org/fulib/fx/app/FrameworkTest.java
> +        // TODO assertThrows(IllegalControllerException.class, () -> app.show("/controller/nonextending"));
In general, we should either remove the test entirely or "fix" the issues instead of leaving todos in the code.

2024-04-06 18:13 UTC, LeStegii commented on annotation-processor/src/main/java/org/fulib/fx/FxClassGenerator.java
> +    }
This currently doesn't support super classes.
If no default resource bundle is set and the bundle is located in a super class (see ludo example), the generated class doesn't work during runtime as the bundle method returns null.

2024-04-06 18:14 UTC, LeStegii commented on annotation-processor/src/main/java/org/fulib/fx/FxClassGenerator.java
> +
(Same for some other methods as well)

2024-04-12 15:10 UTC, Clashsoft commented
@LeStegii Please add a check/warning for private fields and methods with our annotations. Feel free to add to this PR or merge first and create a new one.

2024-04-15 19:44 UTC, Clashsoft commented on framework/src/main/java/org/fulib/fx/util/ReflectionUtil.java
> +            return true;
filter with return true is not the best operation here, better use peek

2024-04-15 19:44 UTC, Clashsoft commented on framework/src/main/resources/org/fulib/fx/lang/error.properties
> +1012=%s '%s' in class '%s' annotated with '%s' cannot be accessed as it is private.
Simpler wording would be `Cannot access private %s '%s' in class '%s' annotated with '%s'`

2024-04-15 19:44 UTC, Clashsoft commented on ludo/src/main/java/de/uniks/ludo/controller/IngameController.java
> +    public void rollDice() {
package-private is also fine and should be our best practice -- it is the lowest visibility that works.

2024-04-15 19:44 UTC, Clashsoft commented on ludo/src/main/java/de/uniks/ludo/controller/IngameController.java
> +    public void displayCurrentTurn() {
dito

2024-04-15 19:44 UTC, Clashsoft commented on framework/src/main/java/org/fulib/fx/controller/internal/ReflectionSidecar.java
> +        for (Field field : ReflectionUtil.getAllNonPrivateFieldsOrThrow(instance.getClass(), Param.class).toList()) {
Just realized this could be changed to stream.forEach to avoid the intermediate list

2024-04-15 19:44 UTC, Clashsoft commented on framework/src/main/java/org/fulib/fx/controller/internal/ReflectionSidecar.java
> +        for (Field field : ReflectionUtil.getAllNonPrivateFieldsOrThrow(instance.getClass(), ParamsMap.class).toList()) {
Dito

2024-04-15 19:44 UTC, Clashsoft commented on ERROR_CODES.md
> +- Annotation Processor: ❌(Caught by the compiler)
This was only incidentally not removed by the Action script. We should just add a proper diagnostic in the ControllerAnnotationProcessor even if that is somewhat redundant.

2024-04-16 14:17 UTC, merged