Fix/override annotations
fujaba/fulibFx pull request #90
Opened 2024-05-06 11:39 UTC by LeStegii

If a method is annotated with an event annotation such as `@OnInit` and is overriding a method from a super class which is also annotated with an event annotation, the method in the class will be called twice due to how java handles overwriting methods.

Therefore, overriding an event method shouldn't be allowed and will result in the following error:
`Method 'destroy' annotated with 'OnDestroy' in class 'de.uniks.ludo.controller.SetupController' overrides event method in class 'de.uniks.ludo.controller.BaseController'.`

- [x] Check method overrides in reflection sidecar
- [ ] Check method overrides in processor sidecar

2024-05-07 14:19 UTC, LeStegii commented
Everything should now work as expected. However, when there is a chain of inheriented classes like `Parent.class` -> `Sub.class` -> `SubSub.class` which override each others methods, some error messages can be duplicated.

While this doesn't affect the process itself, it could be harder to read the error in certain conditions.

![grafik](https://github.com/fujaba/fulibFx/assets/50475262/59b8aefb-3155-4bf0-a869-e5260333b035)

2024-05-07 14:27 UTC, Clashsoft commented on annotation-processor/src/main/java/org/fulib/fx/FxClassGenerator.java
> +                                        streamAllMethods(e, OnKey.class)
It would be far more efficient to iterate over all super methods, check if the name matches, then check if the super method has any event annotation.

2024-05-07 20:56 UTC, Clashsoft requested changes

2024-05-07 20:56 UTC, Clashsoft commented on annotation-processor/src/main/java/org/fulib/fx/ControllerAnnotationProcessor.java
> +                .ifPresent(overriddenMethod -> processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, error(1013).formatted(method, element.getQualifiedName(), ((TypeElement) overriddenMetho
Please refactor this into a lambda with braces { } and perhaps a few variables. Currently the line is way to long.

2024-05-07 20:56 UTC, Clashsoft commented on annotation-processor/src/main/java/org/fulib/fx/ControllerAnnotationProcessor.java
> +                .filter(this::isEventMethod)
I don't like how this has to run once for every single event-annotated method in the child class. Maybe a list or map of event methods in the parent class could be precomputed.

2024-05-07 20:56 UTC, Clashsoft commented on annotation-processor/src/main/java/org/fulib/fx/ControllerAnnotationProcessor.java
> +    // This will throw an error if the methods are private
Please add a line break in between methods

2024-05-07 20:56 UTC, Clashsoft commented on annotation-processor/src/main/java/org/fulib/fx/ControllerAnnotationProcessor.java
> +                processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, error(1012).formatted(Method.class.getSimpleName(), method.getSimpleName(), componentClass.getQualifiedName(), annotati
Will this not potentially report the same error multiple times? I would keep this a pure (as in, no side effects) helper method and do the reporting elsewhere.

2024-05-07 20:56 UTC, Clashsoft commented on annotation-processor/src/main/java/org/fulib/fx/ControllerAnnotationProcessor.java
> +            if (field.getModifiers().contains(Modifier.PRIVATE)) {
Same here

2024-05-07 20:56 UTC, Clashsoft commented on annotation-processor/src/main/java/org/fulib/fx/FxClassGenerator.java
> +    public FxClassGenerator(ControllerAnnotationProcessor processor, ProcessingEnvironment processingEnv) {
I generally like this refactoring, but I believe we should have a third class to not overgrow the ControllerAnnotationProcessor class (which, going by the name, already does way more than it should).

2024-05-08 15:32 UTC, Clashsoft requested changes

2024-05-08 15:32 UTC, Clashsoft commented on annotation-processor/src/main/java/org/fulib/fx/FulibFxProcessor.java
> +            .collect(groupingBy(method -> (TypeElement) processingEnv.getTypeUtils().asElement(method.getEnclosingElement().asType())));
Sorry I was not clear about this. I'd rather use the method name as the key, as that is faster to look up.
Also, you seem to have a double conversion here (enclosing element -> type -> element)

2024-05-08 15:32 UTC, Clashsoft commented on annotation-processor/src/main/java/org/fulib/fx/FulibFxProcessor.java
> +            );
Please don't add unnecessary indentation

2024-05-08 16:22 UTC, Clashsoft requested changes

2024-05-08 16:22 UTC, Clashsoft commented on annotation-processor/src/main/java/org/fulib/fx/FulibFxProcessor.java
> +        if (eventMethods.containsKey(method.getSimpleName().toString())) {
Small refactoring: this should have early return, and the simple name tostring should be in a variable instead of being repeated

2024-05-08 16:22 UTC, Clashsoft commented on annotation-processor/src/main/java/org/fulib/fx/FulibFxProcessor.java
> +                String kind = element.getKind() == ElementKind.METHOD ? Method.class.getSimpleName() : Field.class.getSimpleName();
perhaps toLowerCase to not seem out of place? or just use string literals, its not like this is gonna change ^^

2024-05-08 16:41 UTC, Clashsoft approved these changes

2024-05-08 16:41 UTC, merged